settings:
    log_level: ENC[AES256_GCM,data:EHCG8A==,iv:MipjCbXZlDWtEd+hNbpTYFWn6V4tNUy8CdTgBt5yDEc=,tag:QgZeUx5HQayV7zvD1QN1iQ==,type:str]
    update_period: ENC[AES256_GCM,data:AzY=,iv:yBk965qeSWMZnqeHBanxUs9R8ADzC0v798ZEHp5DvkE=,tag:zjrX7n5T6CVVOSXD4/YjGw==,type:str]
domains:
    - provider: ENC[AES256_GCM,data:dhU5vtxz4NykwA==,iv:hT7uCwyHTW6wHo99pTk94jAeuFOcXTgEKTpiO2ew558=,tag:ZtelRYe+oHcHKWK40SRrHw==,type:str]
      domain: ENC[AES256_GCM,data:EOV08qLdzfqfjQ==,iv:QeLQp+ieDVY6gkHscHepEorE3X2tRTLVEqwnHAOZ+mY=,tag:J/h5Px0wIlW1uxbBaKaygw==,type:str]
      host: ENC[AES256_GCM,data:iUqEiRA=,iv:tDJq9ALatvBQndHC7gTbESGxPj4rAeNgebdbrQac2Zw=,tag:7YWpRviHBeNOA8z5/YSBdQ==,type:str]
      ip_version: ENC[AES256_GCM,data:piaOBA==,iv:LrDy/tRRTyqZUgwf4QtRWQdD/x0xGv5mZ+70YC7Vqhs=,tag:jMmPpqo/Sa13dw4YxSE2hw==,type:str]
      cloudflare_zone_identifier: ENC[AES256_GCM,data:0nMjF9jaJhkmBg==,iv:SbvXmejarONc7HZBGwZP8OFR+JVJeYIzQmf3pCXPOmg=,tag:AkslNOgrfB4OOCywgz0u0w==,type:str]
      cloudflare_auth_token: ENC[AES256_GCM,data:O3Qb218eD1oX+9DhpSKi1t7RosRCgNHbLVhblkL88+vNXC4yuiu35Q==,iv:ihTnlP4dRtJIznI5kijCqjXncypMu3ULA1sy2bSMHq4=,tag:MMWmgRjUWSRgESFFs9oaUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhzexhln9y5nvlgxrxu4ly7q903xhfujf6gqh2ltp7rfnu7crs2qvs0p24
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY2tEQ3diMTBQZVNWWHEz
            d21Ga1RIQ3JNT0s1VGg5cDlNNDhyaGRyelFzClgyU3NRbW5JUTBJQWVKQU9uZ05j
            T2FSdmNDSTd2RTY3eG5LQVdnZjd2QlUKLS0tIC9ra1E4dlA5cE5VQWhwK0dkWTM0
            TGJVYWNEZE9aaVBKZkpwQTdxaGxVWTgKhrWOIE+W4JUAXjkWjDek9AOG35nN2nb1
            xgF1EabfqFdzQUT+JdZt4dtUuGo1umb3pwyJgtejNivpl5jtf/zG6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T10:33:30Z"
    mac: ENC[AES256_GCM,data:F4dZGnUZIcrJTNIlPd94UL8z44Nk/jYvvCJB8ybJhTpGAKXkAElCF5RvMvqeojQa4/TIdCvAlcTgD/hCROKJjpf52pz5Sqd2ue3Q8lyGC2Oj43lmcmnQAW/4nm+C0UNFMfUilspV5nv3bjUJsldgMczgljuzUDY8a++uNOx8M0I=,iv:oPj/6sTJateMM8OUoWWQslS/wWja/mh2C4fixrkeNuE=,tag:el8g2MMAxh04xzc7Sg91dg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
